name: intermediate environment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }}
      BIZEN: ${{ vars.BIZEN }}
      PASS: ${{ secrets.SHONAI }}
    steps:
      - run: echo "${ACTOR}"
      - run: echo "${BIZEN}"
      - run: echo "${PASS}"
