name: Hello # workflow_name
on: push    # event
jobs: # job-id
  hello:
    runs-on: ubuntu-latest # ランナー jobの実行環境
    steps: # ステップ
      - name: init
        run: echo "hello, world!!"  # workflow最小単位
      - uses: actions/checkout@v4 # action実行  
      - name: Otameshi
        run: |
         git long -l
         tree -a
