name: Static analysis
on:
  pull_request:
    paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml']
defaults:
  run:
    shell: bash
concurrency: # 自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  int:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Run static analysis
        run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhsd/actionlint:latest

